resources:
  - name: mydotnetrepo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: nethrasruthinethra # replace jfrog with your username or org name
      branches:
        include: master
        
  - name: mydotnetinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: sample
      buildName: Testapp
  
  pipelines: 
  - name: dotnet-core-hello-world
    configuration:
       
    steps:
      - name: build-service
        public: true
        serial: true
  plan:
      - get: service-repo
        trigger: true
      - task: build-and-pkg
        file: service-repo/ci/tasks/build.yml
      - put: deploy-dev-env
        params:
        manifest: service-repo/manifest.yml

      
      
      
      
      
           
